%YAML:1.1
robot_id: 1
#0 define enemy is red......1 define enemy is blue.
enemy_is_red: 1
#是否使用相机自带的sdk，0为不使用，1为使用
use_camera_sdk: 1
#dev path
serial_path: "/dev/xRMRobotSP"
capture_path : "/dev/video0"
